### ISSUE TITLE
Download old version

### ISSUE THREAD

**Issue by neversay** [dpjanes/homestar-wemo#2]
It is a little bit weird since the version is on 0.0.6, the result of 'homestar install homestar-wemo' is different on different environments.
On my Mac, it loads the module with version 0.0.6 and with latest code.

On my Raspberry PI, the command loads a version 0.0.6 but the code is old ( at version https://github.com/dpjanes/homestar-wemo/tree/8fc7c0e7c88c5bf6a1ac664692773fcb815ec5e9 )

Cannot explain why......

**Comment by neversay** [comment]
Interesting, In my Raspberry PI, I use git clone to get latest version and use 'ln -s' to link the library into the homestar folder, it can display multiple state now:
![screen shot 2015-03-02 at 11 11 46 pm](https://cloud.githubusercontent.com/assets/1990056/6457893/8e65fe16-c131-11e4-9b9d-b3ed77ae21e9.png)

Just curious is it a plan that keep the version of homestar sync with the version in npm ? Thanks!

**Comment by neversay** [comment]
In my project I have to use 'homestar install' to install all necessary package into my package, which means npm does not work and will not work. Is any reason why homestar does not use normal npm to install those submodules? Just curious.

**Comment by neversay** [comment]
After some investigation, the result in my project is:
1. install homestar-wemo with homestar install -- It works perfectly.
2. install homestar-wemo from git with latest version -- when I call things = iot.connect() I can see the WeMo Insight is listed in things, but no response when calling things.set(':on', true) , that means the command does not compose correct with homestar 0.0.55 .

**Comment by neversay** [comment]
The only different on my Mac and Raspberry is the version of npm.

In Mac it is 1.4.3 and in my Raspberry it is 2.5.1. the package.json in homestar-wemo is different, I wonder if the latest npm does not support what homestar need:

Package.json downloaded with npm 1.4.3:
https://gist.github.com/neversay/526a07f76c6e14f844a6

Package download with npm 2.5.1:
https://gist.github.com/neversay/289c8ce27c253baf8e3c

**Comment by dpjanes** [comment]
1) The plan is not to put versions into NPM for test bug fixes, but to otherwise keep them up to date. 
2) I'm doing everything 2.5.1 - weird that it's getting the wrong package version for earlier version

I'm actually quite happy with homestar-install, which really is just a light wrapper over "npm install". It does the following
- it maintains the list of installed modules in .iotdb/keystore.json 
  --- when IOTDB starts up, it loads the list modules
  --- the "setup" function will be called, if it exists
  --- they'll be loaded, all the bindings will be loaded, and so forth

This is modelled on Atom (the editor), which does something similar though I don't know the exact mechanism they use and was suggested to me by Neil Bartlett. 

It also does one more thing: if a homestar module requires another homestar module, instead of it letting "hide" as a nested module, it brings it up to the top level. This is because there's no way for things like "iotdb-upnp" to work without everyone sharing a consistent version of the world. You'll also be able to require Models from other packages, and once again it's important that there be a single consistent view of things.

We're going to make a lot more use of this going forth. For example, you'll be able to load in new "interactors" so you could e.g. change the way colors are selected, or make a complete portable UI for one particular thing you have.

**Comment by dpjanes** [comment]
You should also be able to do github installs BTW!

homestar install dpjanes/node-iotdb
homestar install dpjanes/iotdb-upnp
homestar install dpjanes/homestar-wemo

**Comment by dpjanes** [comment]
1) did IOTDB ever control your Insight?
2) can you run dpjanes/homestar-wemo/samples/iotdb_insight.js for a minute and mail me the logs davidjanes@davidjanes,com

**Comment by dpjanes** [comment]
Module installation documentation here
https://github.com/dpjanes/iotdb-homestar/blob/master/docs/command-install.md

**Comment by neversay** [comment]
1) I use homestar install homestar-wemo , and that version does not work because it does not recognize WeMo Insight, I have to add the _is_supported() back into the WeMoSocketBridge.js to make iotdb detect it. Since it downloaded old version ( 0.0.6 without my PR, so weird)
2) will try to run the script when I at home

And BTW, regarding of the unique iotdb-upnp, maybe you dont need to use a script to remove all other installed sub module across all homestar-\* module, how about try peerDependency? 
http://blog.nodejs.org/2013/02/07/peer-dependencies/

If all of your homestar-\* and iotdv-homestar declare the same iotdb-upnp, it should only contain one instance on the root of node_modules/

**Comment by dpjanes** [comment]
If _is_supported() is missing, then WeMoInsight model will be too (?). Try
"homestar install dpjanes/homestar-wemo" instead?

Thanks for that other bit. Sheesh, a lot of coding on my part for nothing.
Will adapt to this

**Comment by neversay** [comment]
Yap, whole models is even not existing in my downloaded npm package. So weird, it looks like it downloaded whole package in version https://github.com/dpjanes/homestar-wemo/tree/58db8305ec3a8fd69e633ecb721e529b6b347b59  even in my package.json it shows I downloaded version 0.0.6.

And for the peerDependency I dont know if it work as your expectation, so you might need to write some sample code to ensure it works as what you and I think it should be.

**Comment by dpjanes** [comment]
Just for fun I uploaded a new homestar-wemo package (0.0.7) even though I
didn't change anything.

peerDependency definitely is what I'm looking for, though I still need
"homestar install" to track plugins.

D.

**Comment by neversay** [comment]
I can download 0.0.7  now, the code is latest :)

**Comment by dpjanes** [comment]
If you get a chance, can you try the latest version - I just pushed a big updated to IOTDB. I'd send you an email directly but I don't have your contact info.
